letslearn/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('tutorials.urls')),
]
if(settings.DEBUG==True):
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tutorials/urls.py
from django.urls import path
from .views import *
app_name = 'tutorial'
urlpatterns = [
    path('',home,name='home'),
    path('tutorials',tut,name='main'),
    path('tutorial/<int:name>',showTut,name='course'),
    path('tutorial/<int:name>/<str:slug>',showchap,name='chapter'),
    path('collection',showCollection,name='collection'),
    path('404',sorryPagenotFound,name='404'),
    path('comming-soon/',CommingSoon,name="comming"),
    path('request',courseRequest,name='request'),
    path('privacy',privacy),
    path('collection/<int:id>',collectionDetail,name="collection-tut")
]

tutorials/models.py
from django.db import models
from ckeditor.fields import RichTextField
import datetime
from django.template.defaultfilters import slugify
# Create your models here.
class Vedios(models.Model):
    identifier =models.CharField(max_length=250,default="Blank")
    video = models.URLField(max_length=500,null=True,blank=True)
    def __str__(self):
        return self.identifier
class Chapter(models.Model):
    title = models.CharField(max_length=45)
    desc = RichTextField(blank=True,null=True)
    video = models.URLField(max_length=500,null=True,blank=True)
    additional_video = models.ManyToManyField(Vedios,blank=True,null=True)
    conclusion = RichTextField(blank=True,null=True)
    identifier = models.CharField(max_length=200,null=True)
    slug =models.CharField(unique=True,null=True,blank=True,max_length=250)
    def __str__(self) -> str:
        return self.identifier
    def save(self,*args,**kwargs):
        slug = slugify(self.title)
        self.slug =f"{self.identifier}-{slug}"
        super(Chapter, self).save(*args, **kwargs)

class Unit(models.Model):
    title =models.CharField(max_length=45)
    chapters =models.ManyToManyField(to=Chapter ,blank=True,through='UnitAndChapter')
    identifier = models.CharField(max_length=200,null=True)
    def __str__(self) -> str:
        return self.identifier
class tutorial(models.Model):
    name =models.CharField(max_length=45)
    desc = models.TextField()
    image=models.ImageField(upload_to='images')
    date =models.DateField(default=datetime.date.today)
    units = models.ManyToManyField(to=Unit,blank=True,through="UnitAndTutorial")
    slug =models.CharField(unique=True,null=True,blank=True,max_length=250)

    def __str__(self) -> str:
        return self.name
    def save(self,*args,**kwargs):
        slug = slugify(self.name)
        super(Chapter, self).save(*args, **kwargs)
class collection(models.Model):
    name =models.CharField(max_length=45)
    image=models.ImageField(upload_to='images')
    desc = models.TextField()
    date =models.DateField(default=datetime.date.today)
    courses = models.ManyToManyField(to=tutorial)    
    slug =models.CharField(unique=True,null=True,blank=True,max_length=250)
    def save(self,*args,**kwargs):
        slug = slugify(self.name)
        super(Chapter, self).save(*args, **kwargs)
    def __str__(self):
        return self.name
class UnitAndTutorial(models.Model):
    Tutorial = models.ForeignKey(to=tutorial,on_delete=models.CASCADE)
    unit = models.ForeignKey(to=Unit,on_delete=models.CASCADE)
    index = models.IntegerField()
    class Meta:
        ordering = ['index']
class UnitAndChapter(models.Model):
    Chapter = models.ForeignKey(to=Chapter,on_delete=models.CASCADE)
    unit = models.ForeignKey(to=Unit,on_delete=models.CASCADE)
    index = models.IntegerField()    

class Request(models.Model):
    name = models.CharField(max_length=250)
    courseName = models.CharField(max_length=250)
    desc =models.TextField()
    date =models.DateField(default=datetime.date.today)

tutorials/views.py
from django.shortcuts import render,redirect
from .models import tutorial,Chapter,Unit,UnitAndChapter,UnitAndTutorial,collection,Request
from .form import requestForm
from django.shortcuts import get_object_or_404
# Create your views here.
def home(request):
    tutorials = tutorial.objects.all()
    req_obj = Request.objects.all()
    return render(request,'home/index.html',{'obj':tutorials,'req':req_obj})

def tut(request):
    tutorials = tutorial.objects.all()
    return render(request,'tutorial/index.html',{'obj':tutorials}) 

def showTut(request,name):
    tut = get_object_or_404(tutorial,id=name)
    try:
        f_unit =UnitAndTutorial.objects.get(Tutorial=tut,index=1)
    except:
        return redirect('tutorial:comming')
    try:
        f_chapter = UnitAndChapter.objects.get(unit=f_unit.unit,index=1).Chapter
    except:
        return redirect('tutorial:comming')
    return redirect('tutorial:chapter',name=name ,slug=f_chapter.slug)

def showchap(request,name,slug):
    obj = []
    next = False
    previous = False
    tut = get_object_or_404(tutorial,id=name)
    chapter = get_object_or_404(Chapter,slug=slug)
    units = tut.units.all()
    c_unit = get_object_or_404(Unit,chapters=chapter)
    index = get_object_or_404(UnitAndTutorial,Tutorial=tut,unit=c_unit).index
    index_2 = get_object_or_404(UnitAndChapter,unit=c_unit,Chapter=chapter).index
    if(index == 1):
        if(index_2 == 1):
            previous = False
        else:
            previous_ch = get_object_or_404(UnitAndChapter,unit=c_unit,index=index_2-1)
            previous ={
                "id":name,
                'chapter':previous_ch.Chapter
            }
        if(not UnitAndChapter.objects.filter(unit=c_unit,index=index_2+1).exists()):
            if(UnitAndTutorial.objects.filter(Tutorial=tut,index=index+1).exists()):
                next_unit = get_object_or_404(UnitAndTutorial,Tutorial=tut,index=index+1).unit
                next_ch = get_object_or_404(UnitAndChapter,unit=next_unit,index=1).Chapter  
                next = {
                "id":name,
                'chapter':next_ch
                }      
        elif(UnitAndChapter.objects.filter(unit=c_unit,index=index_2+1).exists()):
            next_ch = get_object_or_404(UnitAndChapter,unit=c_unit,index=index_2+1).Chapter  
            next = {
                "id":name,
                'chapter':next_ch
            }  
        else:
            next =False
    else:
        if(index_2 == 1):
            c_unit_previos =get_object_or_404(UnitAndTutorial,Tutorial=tut,index=index-1)
            previous_ch = get_object_or_404(UnitAndChapter,unit=c_unit_previos.unit).last()
            previous ={
                "id":c_unit_previos.Tutorial.id,
                'chapter':previous_ch.Chapter
            }
        else:
            previous_ch = get_object_or_404(UnitAndChapter,unit=c_unit,index=index_2-1)
            previous ={
                "id":name,
                'chapter':previous_ch.Chapter
            }
        if(not UnitAndChapter.objects.filter(unit=c_unit,index=index_2+1).exists() and UnitAndTutorial.objects.filter(Tutorial=tut,index=index+1).exists()):
            c_unit_next =get_object_or_404(UnitAndTutorial,Tutorial=tut,index=index+1)
            next_ch = get_object_or_404(UnitAndChapter,unit=c_unit_next.unit,index=1).Chapter
            next ={
                "id":c_unit_next.Tutorial.id,
                'chapter':next_ch
            }           
        elif(UnitAndChapter.objects.filter(unit=c_unit,index=index_2+1).exists()):
            next_ch =get_object_or_404(UnitAndChapter,unit=c_unit,index=index_2+1).Chapter  
            next = {
                "id":name,
                'chapter':next_ch
            }        
    for i in units:
        chapters = i.chapters.all()
        objs = {
            "id" : i.id,
            'title':i.title,
            "chapters" : chapters
        }
        obj.append(objs)
    return render(request,'chapter.html',{'data':obj,'ch':chapter,'tutorialname':tut.name,'name':name,"next":next,"previous":previous})

def showCollection(request):
    obj = collection.objects.all()
    return render(request,'collection/collection.html',{'obj':obj})
def collectionDetail(request,id):
    obj = get_object_or_404(collection,id=int(id)).courses.all()
    return render(request,'collection/collection_detail.html',{'obj':obj})
def sorryPagenotFound(request):
    return render(request,'404.html')
def CommingSoon(request):
    return render(request,'Comming Soon.html')
def courseRequest(request):
    myform = requestForm()
    if(request.method == "POST"):
        form =requestForm(request.POST)
        if(form.is_valid()):
            form.save()
            return redirect("tutorial:home")
        return render(request,"request.html",{'form':form})
    return render(request,"request.html",{'form':myform})
def privacy(request):
    return render(request,'privacy.html')

tutorials/templates/collection/collection.html
{%extends 'backend.html'%}
{%block content%}
{%load static%}
{%include "navbar5.html" %}
<div class="px-5 mt-5 mb-5">
  <h1 class="entry">Collections</h1>
  <div class="d-flex gap">
      {%for o in obj%}
      <div class="card length px-0" >
          <img class="card-img-top img-self" src="{%get_media_prefix%}{{o.image}}" alt="Card image cap">
          <div class="card-body">
            <h2 class="card-title">{{o.name}}</h2>
            <p class="my-card-text">{{o.desc}}</p>
            <button  class="btn btn-primary"><a href="{%url 'tutorial:collection-tut' id=o.id  %}" class="null">>> Go to</a></button>
          </div>
        </div>
      {%endfor%}
  </div>
</div>
<section class="whyUs-section">
  <div class="cont">
      <div class="featured-points">
          <ul>
              <li><i class="fas fa-money-check-alt"></i> completely Free </li>
              <li><i class="fas fa-book"></i>aceessible with easy</li>
              <li><i class="fas fa-chalkboard-teacher"></i> orginized with chapters and units</li>
          </ul>
      </div>
            <div class="whyus-wrap">
                <h2>About Me?</h2>
                <p itemprop="description" style="margin-bottom: 2rem;">I am a programmer in love with learning and evoliving in the world of tech. been programming seens I was 13 (now 18) so I wanted to share something to the community. So here I am with a simple website which will allow other people learn coding faster and efficiently</p>
            </div>
  </div>
</section>
{%endblock%}
{%block js%}
<style>
    .entry{
        font-size: 4rem;
        font-weight: 600;
        font-family: Arial, Helvetica, sans-serif;
        text-align: center;
        margin-bottom: 1.5rem;
    }
    .null{
        all: unset;
        color: white;
        font-size: 1.2rem;
    }
    .my-card-text{
        font-size: 1.3rem;
        line-height: 16px;
    }
    .length{
        max-width:300px;
        margin-bottom: 2rem;
    }
    .gap{
        justify-content: center;
        gap: 5%;
    }
    .img-self{
        width: 100%;
		height: 280px;
        object-fit:cover;
	}
    @media screen and (max-width:1138px) {
        .gap{
            gap: 8%;
        }
    }
    @media screen and (max-width:600px) {
       .length{
        max-width: 80%;
       }
       .img-self{
        width: 100%;
		height: 310px;
        object-fit:cover;
	}
    }
</style>
{%endblock%}

tutorials/templates/collection/collection_detail.html
{%extends 'backend.html'%}
{%load static%}
{%block content%}
{%include 'navbar2.html'%}
<div class="px-5 mt-5 mb-5">
    <h1 class="entry">Tutorials</h1>
    <div class="row gap">
        {%for o in obj%}
        <div class="card length px-0" >
            <img class="card-img-top img-self" src="{%get_media_prefix%}{{o.image}}" alt="Card image cap">
            <div class="card-body">
              <h2 class="card-title">{{o.name}}</h2>
              <p class="my-card-text">{{o.desc}}</p>
              <button  class="btn btn-primary"><a href="{%url 'tutorial:course' name=o.id %}" class="null">Go to tutorial</a></button>
            </div>
          </div>
        {%endfor%}
    </div>
</div>
<section class="whyUs-section">
    <div class="cont">
        <div class="featured-points">
            <ul>
                <li><i class="fas fa-money-check-alt"></i> completely Free </li>
                <li><i class="fas fa-book"></i>aceessible with easy</li>
                <li><i class="fas fa-chalkboard-teacher"></i> orginized with chapters and units</li>
                <li> <i class="fas fa-book"></i> amazing projects at the end of each unit</li>
            </ul>
        </div>
        <div class="whyus-wrap">
            <h2>About Me?</h2>
            <p itemprop="description">I am a lone programmer that just wanted to organize the amazing different tutorial avaliable on youtube. When you go to the tutorial side you will see what I am talking about, try to enjoy it. It's is completely free and good luck</p>

        </div>
    </div>
</section>
<section class="whyUs-section">
    <div class="cont">
        <div class="featured-points">
            <ul>
                <li><i class="fas fa-money-check-alt"></i> completely Free </li>
                <li><i class="fas fa-book"></i>aceessible with easy</li>
                <li><i class="fas fa-chalkboard-teacher"></i> orginized with chapters and units</li>
            </ul>
        </div>
            <div class="whyus-wrap">
                <h2>About Me?</h2>
                <p itemprop="description" style="margin-bottom: 2rem;">I am a programmer in love with learning and evoliving in the world of tech. been programming seens I was 13 (now 18) so I wanted to share something to the community. So here I am with a simple website which will allow other people learn coding faster and efficiently</p>
            </div>
    </div>
</section>
{%endblock%}
{%block js%}
<style>
    .entry{
        font-size: 4rem;
        font-weight: 600;
        font-family: Arial, Helvetica, sans-serif;
        text-align: center;
        margin-bottom: 1.5rem;
    }
    .null{
        all: unset;
        color: white;
        font-size: 1.2rem;
    }
    .my-card-text{
        font-size: 1.3rem;
        line-height: 16px;
    }
    .length{
        max-width:300px;
        margin-bottom: 2rem;
    }
    .gap{
        justify-content: center;
        gap: 5%;
    }
    .img-self{
        width: 100%;
		height: 280px;
        object-fit:cover;
	}
    @media screen and (max-width:1138px) {
        .gap{
            gap: 8%;
        }
    }
    @media screen and (max-width:600px) {
       .length{
        max-width: 80%;
       }
       .img-self{
        width: 100%;
		height: 310px;
        object-fit:cover;
	}
    }
</style>
{%endblock%}