letslearn/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('tutorials.urls')),
]
if(settings.DEBUG==True):
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tutorials/urls.py
from django.urls import path
from .views import *
app_name = 'tutorial'
urlpatterns = [
    path('',home,name='home'),
    path('tutorials',tut,name='main'),
    path('tutorial/<int:name>',showTut,name='course'),
    path('tutorial/<int:name>/<str:slug>',showchap,name='chapter'),
    path('collection',showCollection,name='collection'),
    path('404',sorryPagenotFound,name='404'),
    path('comming-soon/',CommingSoon,name="comming"),
    path('request',courseRequest,name='request'),
    path('privacy',privacy),
    path('collection/<int:id>',collectionDetail,name="collection-tut")
]

templates/backend.html
{%load static %}
{% load google_analytics_gtag %}
<!DOCTYPE html>
<html lang="en">
<head>
	{% google_analytics_gtag %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" 
	content="Introducing Abyisina Coding, the revolutionary platform that transforms scattered Tutorials videos into structured learning experiences. We organize every tutorial into clear, timestamped chapters, allowing you to jump directly to relevant topics, review specific techniques, and accelerate your coding journey">
    <meta itemprop="name" content="Abyisina Coding" />
	<meta itemprop="description" content="Introducing Abyisina Coding, the revolutionary platform that transforms scattered Tutorials videos into structured learning experiences. We organize every tutorial into clear, timestamped chapters, allowing you to jump directly to relevant topics, review specific techniques, and accelerate your coding journey" />
	<meta itemprop="image" content="{%static 'images/js.png'%}" />
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css" integrity="sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
	{%block styleimport %}
	{%endblock styleimport %}
	<style>
	.cbe-icon{
        width: 23px;
        height: 23px;
        margin-left:25px ;
    }
	</style>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/rateYo/2.3.2/jquery.rateyo.min.css" integrity="sha512-Xok8TFWv6SGkmjTO0s+Tfitu6XRaCuuT1k9sgGhhFZIFCldQuqa6y8MMnlqEWwWRJgXnJQQ2AcOJc/JpyedliA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
	<link rel="stylesheet" type="text/css" href="{%static 'inner-page-style.css' %}">
    <link rel="icon" type="image/x-icon" href="{%static 'images/js.png'%}">
	<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
	<link href="https://cdn.lineicons.com/4.0/lineicons.css" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
	<link href="https://fonts.googleapis.com/css?family=Raleway:400,500,600,700" rel="stylesheet">
	<link rel="stylesheet" href="{% static 'ckeditor/ckeditor/plugins/codesnippet/lib/highlight/styles/monokai.css' %}" />
	<title>
		{%block title%}
		{%endblock%}
	</title>
    {%block js%}
{%endblock%}
</head>
<body>
    {%block content%}

    {%endblock%}

	<script src="https://code.jquery.com/jquery-3.3.1.min.js" ></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/rateYo/2.3.2/jquery.rateyo.min.js"></script>
    <script src="{% static 'ckeditor/ckeditor/plugins/codesnippet/lib/highlight/highlight.pack.js' %}"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/js/all.min.js" integrity="sha512-b+nQTCdtTBIRIbraqNEwsjB6UvL3UEMkXnhzd8awtCYh0Kcsjl9uEgwVFVbhoj3uu1DO1ZMacNvLoyJJiNfcvg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
	{%block scriptimport%}
	{%endblock scriptimport%}
	<script type="text/javascript" src="{% static 'js/custom.js' %}"></script>
	<script>hljs.initHighlightingOnLoad();</script>

</body>

{%block css%}

{%endblock%}

</html>

templates/navbar.html
{%load static%}
<header class="site-header">
    <div class="top-header">
        <div class="cont">
            <div class="top-header-left ">
                <div class="top-header-block">
                    <a href="tel:+251972692781" itemprop="telephone"><i class="fas fa-phone"></i> +251 972692781</a>
                    <a style="margin-left: 1.3rem;" class="icon-resize" href="https://t.me/Lets_learnCoding"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 496 512"><path fill="currentColor" d="M248 8C111 8 0 119 0 256S111 504 248 504 496 393 496 256 385 8 248 8zM363 176.7c-3.7 39.2-19.9 134.4-28.1 178.3-3.5 18.6-10.3 24.8-16.9 25.4-14.4 1.3-25.3-9.5-39.3-18.7-21.8-14.3-34.2-23.2-55.3-37.2-24.5-16.1-8.6-25 5.3-39.5 3.7-3.8 67.1-61.5 68.3-66.7 .2-.7 .3-3.1-1.2-4.4s-3.6-.8-5.1-.5q-3.3 .7-104.6 69.1-14.8 10.2-26.9 9.9c-8.9-.2-25.9-5-38.6-9.1-15.5-5-27.9-7.7-26.8-16.3q.8-6.7 18.5-13.7 108.4-47.2 144.6-62.3c68.9-28.6 83.2-33.6 92.5-33.8 2.1 0 6.6 .5 9.6 2.9a10.5 10.5 0 0 1 3.5 6.7A43.8 43.8 0 0 1 363 176.7z"/></svg>Telegram</a>
                </div>
            </div>
            <div class="top-header-right">
                <div class="social-block">
                    <ul class="social-list">
                        <button class="btn btn-primary"><a class="a-null" href="{%url 'tutorial:request'%}">Request a Course</a></button>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- Top header Close -->
    <div class="main-header position-relative">
        <div class="container-md d-flex justify-content-between p-1 px-5 ">
            <div class="logo-wrap" itemprop="logo">
                <img class="logo-resize" src="{%static 'images/site-logo.png'%}" alt="Logo Image">
                <!-- <h1>Education</h1> -->
            </div>
            <div class="nav-wrap">
                <nav class="nav-desktop nav-postion">
                    <ul class="menu-list">
                        <li><a   class="active">Home</a></li>
                        <li><a id="tut" href="{%url 'tutorial:main'%}">Tutorial</a></li>
                        <li><a id="tut" href='{%url "tutorial:collection"%}'>Collections</a></li>
                    </ul>
                </nav>
                <div id="bar">
                    <i class="fas fa-bars"></i>
                </div>
                <div id="close">
                    <i class="fas fa-times"></i>
                </div>
            </div>
        </div>
    </div>
</header>
<style>
        .active{
        color: rgb(125, 125, 125) !important;
        text-decoration: none !important;
    }
    .active:hover{
        cursor:default !important;
    }

    @media  screen and (max-width:1024px) {        
        .nav-postion{
            position: absolute;
            left: 0;
            top:90%;
            background-color: whitesmoke;
            width: 100%;
            border-radius: 5px;
            z-index: 10;
            padding-top: 10px;
        }
    }
    .icon-resize svg{
        width: 13px;
        height: 13px;
       color: white;
    }
</style>

templates/navbar2.html
{%load static%}
<header class="site-header">
    <div class="top-header">
        <div class="cont">
            <div class="top-header-left ">
                <div class="top-header-block">
                    <a href="tel:+251972692781" itemprop="telephone"><i class="fas fa-phone"></i> +251 972692781</a>
                </div>
            </div>
            <div class="top-header-right">
                <div class="social-block">
                    <ul class="social-list">
                        <button class="btn btn-primary"><a class="a-null" href="{%url 'tutorial:request'%}">Request a Course</a></button>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- Top header Close -->
    <div class="main-header position-relative border-bt">
        <div class="container-md d-flex justify-content-between p-2 px-5 ">
            <div class="logo-wrap " itemprop="logo">
                <img class="logo-resize" src="{%static 'images/site-logo.png'%}" alt="Logo Image">
                <!-- <h1>Education</h1> -->
            </div>
            <div class="nav-wrap">
                <nav class="nav-desktop nav-postion">
                    <ul class="menu-list">
                        <li><a  href="{%url 'tutorial:home'%}" >Home</a></li>
                        <li><a class="active">Tutorial</a></li>
                        <li><a href='{%url "tutorial:collection"%}'>Collections</a></li>
                    </ul>
                </nav>
                <div id="bar">
                    <i class="fas fa-bars"></i>
                </div>
                <div id="close">
                    <i class="fas fa-times"></i>
                </div>
            </div>
        </div>
    </div>
</header>
<style>
        .active{
        color: rgb(125, 125, 125) !important;
        text-decoration: none !important;
    }
    .active:hover{
        cursor:default !important;
    }
    @media  screen and (max-width:1024px) {        
        .nav-postion{
            position: absolute;
            left: 0;
            top:90%;
            background-color: whitesmoke;
            width: 100%;
            border-radius: 5px;
            z-index: 10;
            padding-top: 10px;
        }
    }
</style>

templates/navbar3.html
{%load static%}
<header class="site-header">
    <div class="top-header">
        <div class="cont">
            <div class="top-header-left ">
                <div class="top-header-block">
                    <a href="tel:+251972692781" itemprop="telephone"><i class="fas fa-phone"></i> +251 972692781</a>
                </div>
            </div>
            <div class="top-header-right">
                <div class="social-block">
                    <ul class="social-list">
                        <button class="btn btn-primary"><a class="a-null" href="{%url 'tutorial:request'%}">Request a Course</a></button>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- Top header Close -->
    <div class="main-header position-relative bt-border">
        <div class="bg-white d-flex justify-content-between p-2 px-5 ">
            <div class="d-flex logo-wrapper">
                <button class="toggle-btn" type="button">
                    <i class="lni lni-grid-alt"></i>
                </button>
                <div class="logo-wrap" itemprop="logo">
                    <h1><a style="color: black;" href="/"><img class="logo-resize" src="{%static 'images/site-logo.png'%}" alt="Logo Image"></a></h1>
                </div>
            </div>
            <div class="nav-wrap">
                <nav class="nav-desktop nav-postion">
                    <ul class="menu-list">
                        <li><a  href="{%url 'tutorial:home'%}" >Home</a></li>
                        <li><a href="{%url 'tutorial:main'%}" >Tutorial</a></li>
                        <li><a href="{%url 'tutorial:collection'%}">Collections</a></li>
                    </ul>
                </nav>
                <div id="bar">
                    <i class="fas fa-bars"></i>
                </div>
                <div id="close">
                    <i class="fas fa-times"></i>
                </div>
            </div>
        </div>
    </div>
</header>
<style>
    .logo-wrapper{
        align-items: center;
    }
    .logo-wrap h1{
        font-size: 18px;
    }
        .active{
        color: rgb(125, 125, 125) !important;
        text-decoration: none !important;
    }
    .active:hover{
        cursor:default !important;
    }
    @media  screen and (max-width:1024px) {        
        .nav-postion{
            position: absolute;
            left: 0;
            top:90%;
            background-color: whitesmoke;
            width: 100%;
            border-radius: 5px;
            z-index: 10;
            padding-top: 10px;
        }
    }
    .bt-border{
        border-bottom: 1px solid rgb(226, 226, 226);
    }
</style>

templates/navbar4.html
{%load static%}
<header class="site-header">
    <div class="top-header">
        <div class="cont">
            <div class="top-header-left ">
                <div class="top-header-block">
                    <a href="tel:+251972692781" itemprop="telephone"><i class="fas fa-phone"></i>+251 972692781</a>
                </div>
            </div>
            <div class="top-header-right">
                <div class="social-block">
                    <ul class="social-list">
                        <button class="btn btn-primary"><a class="a-null" href="{%url 'tutorial:request'%}">Request a Course</a></button>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- Top header Close -->
    <div class="main-header position-relative border-bt">
        <div class="container-md d-flex justify-content-between p-2 px-5 ">
            <div class="logo-wrap" itemprop="logo">
                <img class="logo-resize" src="{%static 'images/site-logo.png'%}" alt="Logo Image">
                <!-- <h1>Education</h1> -->
            </div>
            <div class="nav-wrap">
                <nav class="nav-desktop nav-postion">
                    <ul class="menu-list">
                        <li><a  href="{%url 'tutorial:home'%}">Home</a></li>
                        <li><a href="{%url 'tutorial:main'%}">Tutorial</a></li>
                        <li><a href="{% url 'tutorial:collection'%}">Collections</a></li>
                    </ul>
                </nav>
                <div id="bar">
                    <i class="fas fa-bars"></i>
                </div>
                <div id="close">
                    <i class="fas fa-times"></i>
                </div>
            </div>
        </div>
    </div>
</header>
<style>

        .active{
        color: rgb(125, 125, 125) !important;
        text-decoration: none !important;
    }
    .active:hover{
        cursor:default !important;
    }
    @media  screen and (max-width:1024px) {        
        .nav-postion{
            position: absolute;
            left: 0;
            top:90%;
            background-color: whitesmoke;
            width: 100%;
            border-radius: 5px;
            z-index: 10;
            padding-top: 10px;
        }
    }
</style>

templates/navbar5.html
{%load static%}
<header class="site-header">
    <div class="top-header">
        <div class="cont">
            <div class="top-header-left ">
                <div class="top-header-block">
                    <a href="tel:+251972692781" itemprop="telephone"><i class="fas fa-phone"></i> +251 972692781</a>
                </div>
            </div>
            <div class="top-header-right">
                <div class="social-block">
                    <ul class="social-list">
                        <button class="btn btn-primary"><a class="a-null" href="{%url 'tutorial:request'%}">Request a Course</a></button>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- Top header Close -->
    <div class="main-header position-relative border-bt">
        <div class="container-md d-flex justify-content-between p-2 px-5 ">
            <div class="logo-wrap" itemprop="logo">
                <img class="logo-resize" src="{%static 'images/site-logo.png'%}" alt="Logo Image">
                <!-- <h1>Education</h1> -->
            </div>
            <div class="nav-wrap">
                <nav class="nav-desktop nav-postion">
                    <ul class="menu-list">
                        <li><a  href="{%url 'tutorial:home'%}">Home</a></li>
                        <li><a href="{%url 'tutorial:main'%}">Tutorial</a></li>
                        <li><a class="active">Collections</a></li>
                    </ul>
                </nav>
                <div id="bar">
                    <i class="fas fa-bars"></i>
                </div>
                <div id="close">
                    <i class="fas fa-times"></i>
                </div>
            </div>
        </div>
    </div>
</header>
<style>

        .active{
        color: rgb(125, 125, 125) !important;
        text-decoration: none !important;
    }
    .active:hover{
        cursor:default !important;
    }
    @media  screen and (max-width:1024px) {        
        .nav-postion{
            position: absolute;
            left: 0;
            top:90%;
            background-color: whitesmoke;
            width: 100%;
            border-radius: 5px;
            z-index: 10;
            padding-top: 10px;
        }
    }
</style>